stages:
  - test
  - build
  - release
  - config

test:
  stage: test
  script:
    - echo "some tests should be done..."
  only:
    - branches

build:
  stage: build
  image: jdrouet/docker-with-buildx:20.10.19-0.9.1
  services:
    - docker:20.10-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker buildx create --use
    - docker buildx build --no-cache --target production --platform linux/arm64/v8,linux/amd64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE:latest . --push
  only:
    - tags

release:
  image: node:18
  stage: release
  only:
    refs:
      - master
  script:
    - touch CHANGELOG.md
    - npm install @semantic-release/gitlab @semantic-release/exec @semantic-release/changelog
    - npx semantic-release
  artifacts:
    paths:
      - CHANGELOG.md

# This step updates the helm values and also triggers the update of the acorn application
update config:
  stage: config
  image: lucj/ci:1.0
  script: |
    git config --global user.email "devops@techwhale.io"
    git config --global user.name "TechWhale DevOps"
    git clone --depth 1 https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/voting-application/config.git
    cd config
    yq -i ".${CI_PROJECT_NAME}.tag=\"${CI_COMMIT_TAG}\"" ./helm/values.yaml
    git add ./helm/values.yaml
    git commit -m "fix: update ${CI_PROJECT_NAME} related tag with $CI_COMMIT_TAG in values.yaml"
    git push origin master
  only:
    - tags